sonar.projectKey=lgmohale_capitec-financial-insights-api
sonar.organization=lgmohale
sonar.projectName=capitec-financial-insights-api
sonar.host.url=https://sonarcloud.io

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

sonar.exclusions=.venv/**,migrations/**,alembic/versions/**,data/input/**,data/output/**,**/__pycache__/**
