apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-aggregation-api-config
  namespace: capitec-transaction-aggregation
data:
  APP_NAME: capitec-transaction-aggregation-api
  APP_ENV: local
  MINIO_ENDPOINT: minio
  MINIO_PORT: "9000"
  MINIO_BUCKET: bank-statements
  MINIO_USE_SSL: "false"
