apiVersion: v1
kind: Service
metadata:
  name: transaction-aggregation-api
  namespace: capitec-transaction-aggregation
spec:
  type: ClusterIP
  selector:
    app: transaction-aggregation-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
